use_frameworks!

abstract_target "CoreDuck" do
    pod 'CoreDuck', :path => '../'
    
    target 'CoreDuck-iOS'
    target 'CoreDuck-macOS'
    target 'CoreDuck-Tests'
    
    post_install do |installer|
        installer.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.0'
            end
        end
    end
end
