use_frameworks!

abstract_target 'CoreDuck Example iOS' do
  platform :ios, 8.0
  pod 'CoreDuck', :path => '../'
  target 'CoreDuck_Example'
end

abstract_target 'CoreDuck Example iOS Test' do
  platform :ios, 8.0
  pod 'CoreDuck', :path => '../'
  target 'CoreDuck_Tests'
end