use_frameworks!

target 'CoreDuck_Example' do
  platform :ios, 8.0
  pod 'CoreDuck', :path => '../'

  post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end

end
end

target 'CoreDuck_Example_macOS' do
  platform :osx, '10.11'
  pod 'CoreDuck', :path => '../'

  post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end

end

target 'CoreDuck_Tests' do
  pod 'CoreDuck', :path => '../'

  post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end

end
