language: swift
osx_image: xcode12.2

before_install:
- gem install cocoapods --no-doc --quiet
- gem install xcpretty --no-doc --quiet
- pod --version
- xcpretty --version
- xcodebuild -version
- xcodebuild -showsdks

script:
- set -o pipefail && xcodebuild -workspace Example/CoreDuck.xcworkspace -scheme CoreDuck-iOS -sdk iphoneos14.2 ONLY_ACTIVE_ARCH=NO | xcpretty
- set -o pipefail && xcodebuild -workspace Example/CoreDuck.xcworkspace -scheme CoreDuck-macOS -sdk macosx11.0 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
