language: swift
osx_image: xcode12.2

before_install:
- gem install cocoapods --no-doc --quiet
- gem install xcpretty --no-doc --quiet
- pod --version
- xcpretty --version
- xcodebuild -version
- xcodebuild -showsdks

script:
- set -o pipefail && xcodebuild clean build -workspace Example/CoreDuck.xcworkspace -scheme CoreDuck-iOS -sdk iphonesimulator14.2 PLATFORM_NAME=iphonesimulator ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED="NO" CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO" | xcpretty
- set -o pipefail && xcodebuild clean build -workspace Example/CoreDuck.xcworkspace -scheme CoreDuck-macOS -sdk macosx11.0 ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED="NO" CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO" | xcpretty
- pod lib lint
